version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'tam315'
    groups:
      all-at-once:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '03:00'
      timezone: 'Asia/Tokyo'
    reviewers:
      - 'tam315'
